version: "3"

services:
  test:
    image: golang:1.19.1-alpine
    # TODO: キャッシュする
    volumes:
      - ~/.docker/config.json:/root/.docker/config.json:ro
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CGO_ENABLED=0
      - HOST_DIR=${PWD}
    working_dir: /app
    network_mode: host
